"""initial schema

Revision ID: 747945132f60
Revises: 
Create Date: 2026-06-25 18:55:42.719549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747945132f60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('corp_code', sa.String(length=10), nullable=False),
    sa.Column('region_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('meeting_venue', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='unitstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corp_code')
    )
    op.create_table('divisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('corp_id', sa.UUID(), nullable=False),
    sa.Column('division_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('adult', 'cadet', 'nursing', 'dolphin_pod', name='divisiontype'), nullable=False),
    sa.Column('meeting_venue', sa.String(length=200), nullable=True),
    sa.Column('meeting_day', sa.String(length=20), nullable=True),
    sa.Column('meeting_time', sa.String(length=20), nullable=True),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='unitstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['corp_id'], ['corps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('division_id', sa.UUID(), nullable=False),
    sa.Column('membership_number', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('id_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('employer_or_school', sa.String(length=150), nullable=True),
    sa.Column('next_of_kin_name', sa.String(length=150), nullable=True),
    sa.Column('next_of_kin_phone', sa.String(length=20), nullable=True),
    sa.Column('next_of_kin_relation', sa.String(length=50), nullable=True),
    sa.Column('enrolled_date', sa.Date(), nullable=False),
    sa.Column('current_rank', sa.Enum('member', 'corporal', 'sergeant', 'acting_div_officer', 'div_officer', 'div_superintendent', name='memberrank'), nullable=False),
    sa.Column('specialist_track', sa.Enum('none', 'med_student', 'registered_surgeon', 'nursing_student', 'registered_nursing_officer', 'emt_student', 'registered_paramedic', name='specialisttrack'), nullable=False),
    sa.Column('declaration_signed', sa.Boolean(), nullable=False),
    sa.Column('medically_fit', sa.Boolean(), nullable=False),
    sa.Column('registration_fee_paid_date', sa.Date(), nullable=True),
    sa.Column('photo_url', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'discharged', 'transferred', 'deceased', name='memberstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_number'),
    sa.UniqueConstraint('membership_number')
    )
    op.create_table('award_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('award_name', sa.String(length=200), nullable=False),
    sa.Column('award_category', sa.Enum('meritorious', 'bravery', 'service', 'donation', 'program', 'state_honour', 'divisional', name='awardcategory'), nullable=False),
    sa.Column('awarded_date', sa.Date(), nullable=False),
    sa.Column('awarded_by', sa.String(length=150), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duty_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('duty_date', sa.Date(), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('duty_type', sa.Enum('public_duty', 'community_service', 'divisional_meeting', 'parade', 'training', name='dutytype'), nullable=False),
    sa.Column('hours', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('supervisor', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('efficiency_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('public_duty_hours', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('community_service_hours', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('divisional_meetings_attended', sa.Integer(), nullable=True),
    sa.Column('first_aid_exam_passed', sa.Boolean(), nullable=True),
    sa.Column('annual_parade_attended', sa.Boolean(), nullable=True),
    sa.Column('is_efficient', sa.Boolean(), nullable=True),
    sa.Column('assessed_date', sa.Date(), nullable=True),
    sa.Column('assessed_by', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rank_appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Enum('member', 'corporal', 'sergeant', 'acting_div_officer', 'div_officer', 'div_superintendent', name='memberrank'), nullable=False),
    sa.Column('specialist_rank', sa.Enum('none', 'med_student', 'registered_surgeon', 'nursing_student', 'registered_nursing_officer', 'emt_student', 'registered_paramedic', name='specialisttrack'), nullable=True),
    sa.Column('appointed_date', sa.Date(), nullable=False),
    sa.Column('vacated_date', sa.Date(), nullable=True),
    sa.Column('appointed_by', sa.String(length=150), nullable=True),
    sa.Column('authorization_ref', sa.String(length=100), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.Enum('active', 'suspended', 'discharged', 'transferred', 'deceased', name='memberstatus'), nullable=False),
    sa.Column('new_status', sa.Enum('active', 'suspended', 'discharged', 'transferred', 'deceased', name='memberstatus'), nullable=False),
    sa.Column('changed_date', sa.Date(), nullable=False),
    sa.Column('changed_by', sa.String(length=150), nullable=False),
    sa.Column('bgr_regulation_ref', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_history')
    op.drop_table('rank_appointments')
    op.drop_table('efficiency_records')
    op.drop_table('duty_logs')
    op.drop_table('award_records')
    op.drop_table('members')
    op.drop_table('divisions')
    op.drop_table('corps')
    # ### end Alembic commands ###
